-- =============================================================================
-- SPORTS TICKETING MANAGEMENT SYSTEM
-- File: database/schema.sql
-- Run this file first to create all tables and load sample test data.
-- After testing, truncate all tables and run Python seed scripts.
-- =============================================================================


-- =============================================================================
-- 0. DATABASE
-- =============================================================================

DROP DATABASE IF EXISTS sports_ticketing_db;
CREATE DATABASE IF NOT EXISTS sports_ticketing_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE sports_ticketing_db;


-- =============================================================================
-- 1. SETTINGS
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- =============================================================================
-- 2. DROP EXISTING TABLES (clean slate)
-- =============================================================================

DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS EVENT_SEAT;
DROP TABLE IF EXISTS EVENT_ZONE;
DROP TABLE IF EXISTS BOX_OFFICE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS SEAT;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS STADIUM;


-- =============================================================================
-- 3. TABLE DEFINITIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 3.1 STADIUM
-- Physical venues. One stadium hosts many events and seats.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS STADIUM (
    stadium_id      INT             NOT NULL AUTO_INCREMENT,
    stadium_name    VARCHAR(255)    NOT NULL,
    address         VARCHAR(255),
    capacity        INT UNSIGNED,
    map_image_url   VARCHAR(255),
    created_at      DATETIME        NOT NULL DEFAULT NOW(),
    PRIMARY KEY (stadium_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Physical venues where events are held';


-- -----------------------------------------------------------------------------
-- 3.2 EVENT
-- A match or show held at a stadium.
-- pricing_config: JSON array of dynamic pricing rules evaluated at booking
--   time by the application layer.
-- active_box_offices: JSON array of box_office_id values allowed to sell
--   this event. NULL means all valid channels are allowed (Online always,
--   Venue only if same stadium, Agent always). Set explicitly to restrict.
--   Example: [1, 3] → only box_office_id 1 and 3 can sell this event.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS EVENT (
    event_id             INT          NOT NULL AUTO_INCREMENT,
    stadium_id           INT          NOT NULL,
    event_name           VARCHAR(255) NOT NULL,
    event_date           DATETIME     NOT NULL,
    sale_open_at         DATETIME,
    sale_close_at        DATETIME,
    status               ENUM('Draft','OnSale','SoldOut','Cancelled','Finished')
                                      NOT NULL DEFAULT 'Draft',
    pricing_config       JSON         COMMENT 'Array of pricing rules; evaluated at booking time by Python',
    active_box_offices   JSON         COMMENT 'Array of allowed box_office_id; NULL = all valid channels allowed',
    created_at           DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (event_id),
    KEY idx_event_stadium     (stadium_id),
    KEY idx_event_status_date (status, event_date),
    CONSTRAINT fk_event_stadium
        FOREIGN KEY (stadium_id) REFERENCES STADIUM (stadium_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Events and matches; pricing_config and active_box_offices drive dynamic behaviour';


-- -----------------------------------------------------------------------------
-- 3.3 SEAT
-- Physical seats inside a stadium.
-- seat_type is fixed per seat (row position determines type).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SEAT (
    seat_id         INT             NOT NULL AUTO_INCREMENT,
    stadium_id      INT             NOT NULL,
    seat_row        VARCHAR(10),
    seat_number     VARCHAR(10),
    seat_name       VARCHAR(20)     COMMENT 'Display label generated by Python, e.g. MS1_A01 stand for zone Main Stand - VIP at row A seat 01',
    seat_zone       VARCHAR(100),
    seat_type       ENUM('vip','normal','economy') NULL DEFAULT NULL,
    is_active       TINYINT(1)      NOT NULL DEFAULT 1
                                    COMMENT '0 = seat is broken or closed',
    created_at      DATETIME        NOT NULL DEFAULT NOW(),
    PRIMARY KEY (seat_id),
    KEY idx_seat_stadium (stadium_id),
    CONSTRAINT fk_seat_stadium
        FOREIGN KEY (stadium_id) REFERENCES STADIUM (stadium_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Physical seats; never deleted, only deactivated via is_active';


-- -----------------------------------------------------------------------------
-- 3.4 EVENT_ZONE
-- Defines a named ticket zone per event with a base price.
-- seat_type links zones to seats (one zone per seat type per event).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS EVENT_ZONE (
    zone_id         INT             NOT NULL AUTO_INCREMENT,
    event_id        INT             NOT NULL,
    seat_type       ENUM('vip','normal','economy') NOT NULL,
    zone_name       VARCHAR(100)    NOT NULL
                                    COMMENT 'Display name for this zone, can differ per event',
    base_price      DECIMAL(10,2)   NOT NULL
                                    COMMENT 'Base ticket price in VND before pricing rules apply',
    PRIMARY KEY (zone_id),
    UNIQUE KEY uq_event_zone (event_id, seat_type),
    CONSTRAINT fk_zone_event
        FOREIGN KEY (event_id) REFERENCES EVENT (event_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Per-event zone definitions; one row per seat type per event';


-- -----------------------------------------------------------------------------
-- 3.5 EVENT_SEAT
-- Inventory record for each physical seat within a specific event.
-- Populated by Python when an event goes on sale.
-- locked_by_ticket_id is a soft reference (no FK) to avoid circular dependency.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS EVENT_SEAT (
    event_seat_id       INT         NOT NULL AUTO_INCREMENT,
    event_id            INT         NOT NULL,
    seat_id             INT         NOT NULL,
    zone_id             INT         NOT NULL,
    status              ENUM('Available','Locked','Booked','Unavailable')
                                    NOT NULL DEFAULT 'Available',
    locked_until        DATETIME    COMMENT 'Expiry timestamp for the Locked state',
    locked_by_ticket_id INT         COMMENT 'Soft ref to TICKET; managed by application',
    PRIMARY KEY (event_seat_id),
    UNIQUE KEY uq_event_seat      (event_id, seat_id),
    KEY idx_eventseat_status      (event_id, status),
    KEY idx_eventseat_zone        (zone_id),
    CONSTRAINT fk_eventseat_event
        FOREIGN KEY (event_id) REFERENCES EVENT (event_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_eventseat_seat
        FOREIGN KEY (seat_id) REFERENCES SEAT (seat_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_eventseat_zone
        FOREIGN KEY (zone_id) REFERENCES EVENT_ZONE (zone_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Per-event seat inventory; links physical seats to event-specific zones';


-- -----------------------------------------------------------------------------
-- 3.6 CUSTOMER
-- Registered buyers. Walk-in customers use the pre-seeded anonymous row.
-- password_hash is NULL for walk-in / agent-managed customers.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CUSTOMER (
    customer_id     INT             NOT NULL AUTO_INCREMENT,
    customer_name   VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    COMMENT 'Login credential for online customers',
    phone_number    VARCHAR(20),
    address         VARCHAR(255),
    password_hash   VARCHAR(255)    COMMENT 'Bcrypt hash; NULL for offline customers',
    created_at      DATETIME        NOT NULL DEFAULT NOW(),
    PRIMARY KEY (customer_id),
    UNIQUE KEY uq_customer_email (email),
    UNIQUE KEY uq_customer_phone (phone_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Registered buyers; row 1 is reserved for anonymous walk-in purchases';


-- -----------------------------------------------------------------------------
-- 3.7 BOX_OFFICE
-- Sales channels: website, venue counters, or external agents.
-- stadium_id is set for Venue counters; NULL for Online and Agent.
-- commission_rate is used in revenue-split reports.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS BOX_OFFICE (
    box_office_id   INT             NOT NULL AUTO_INCREMENT,
    office_name     VARCHAR(255)    NOT NULL,
    office_type     ENUM('Online','Venue','Agent') NOT NULL,
    stadium_id      INT             NULL
                                    COMMENT 'Set for Venue counters; NULL for Online and Agent',
    commission_rate DECIMAL(5,2)    NOT NULL DEFAULT 0.00
                                    COMMENT 'Agent commission %; 0 for direct channels',
    address         VARCHAR(255),
    is_active       TINYINT(1)      NOT NULL DEFAULT 1,
    created_at      DATETIME        NOT NULL DEFAULT NOW(),
    PRIMARY KEY (box_office_id),
    CONSTRAINT fk_boxoffice_stadium
        FOREIGN KEY (stadium_id) REFERENCES STADIUM (stadium_id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Sales channels: website, venue counters, external agents';


-- -----------------------------------------------------------------------------
-- 3.8 TICKET
-- Issued after a seat is locked and payment is confirmed.
-- One ticket per event_seat (enforced by unique constraint).
-- qr_code is an opaque random token used for gate scanning.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TICKET (
    ticket_id           INT             NOT NULL AUTO_INCREMENT,
    event_seat_id       INT             NOT NULL,
    customer_id         INT             NOT NULL,
    box_office_id       INT             NOT NULL,
    status              ENUM('Pending','Paid','Cancelled','Expired')
                                        NOT NULL DEFAULT 'Pending',
    price_paid          DECIMAL(12,0)   NOT NULL
                                        COMMENT 'Final price after pricing rules applied',
    price_reason        VARCHAR(255)    COMMENT 'Label from pricing engine, e.g. Early Bird -10%',
    expires_at          DATETIME        COMMENT 'Pending ticket expiry; NULL after payment',
    paid_at             DATETIME,
    qr_code             VARCHAR(128)    COMMENT 'Unique opaque token for gate scanning',
    is_scanned          TINYINT(1)      NOT NULL DEFAULT 0,
    scanned_at          DATETIME,
    created_at          DATETIME        NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticket_id),
    UNIQUE KEY uq_ticket_eventseat (event_seat_id),
    UNIQUE KEY uq_ticket_qrcode    (qr_code),
    KEY idx_ticket_customer        (customer_id),
    KEY idx_ticket_status          (status, expires_at),
    CONSTRAINT fk_ticket_eventseat
        FOREIGN KEY (event_seat_id) REFERENCES EVENT_SEAT (event_seat_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ticket_customer
        FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ticket_boxoffice
        FOREIGN KEY (box_office_id) REFERENCES BOX_OFFICE (box_office_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Confirmed tickets; one per event_seat; qr_code used for gate scanning';


SET FOREIGN_KEY_CHECKS = 1;


-- =============================================================================
-- 4. SAMPLE DATA (for testing only)
-- Truncate all tables and run Python seed scripts for production data.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 4.1 STADIUMS
-- -----------------------------------------------------------------------------
INSERT INTO STADIUM (stadium_name, address, capacity) VALUES
('Wembley Stadium',        'London, United Kingdom', 90000),
('Tokyo Dome',             'Tokyo, Japan',           55000),
('Madison Square Garden',  'New York, USA',          19500);


-- -----------------------------------------------------------------------------
-- 4.2 EVENTS
-- active_box_offices NULL = all valid channels allowed
-- -----------------------------------------------------------------------------
INSERT INTO EVENT (stadium_id, event_name, event_date, sale_open_at, status, pricing_config, active_box_offices) VALUES
(1, 'UEFA Champions League Final 2026',
    '2026-05-30 20:00:00', '2026-03-01 00:00:00', 'OnSale',
    '[
        {"name":"Early Bird",  "type":"days_before", "threshold":60, "modifier_pct":-10},
        {"name":"Last Minute", "type":"days_before", "threshold":3,  "modifier_pct":20}
    ]',
    NULL),   -- all channels allowed
(2, 'Taylor Swift - The Eras Tour (Encore)',
    '2026-08-15 19:00:00', '2026-05-01 09:00:00', 'OnSale',
    '[
        {"name":"High Demand", "type":"sold_pct",    "threshold":85,  "modifier_pct":25},
        {"name":"Hot Selling", "type":"velocity_1h", "threshold":100, "modifier_pct":10}
    ]',
    '[1, 3]'),  -- Online + Ticketmaster only
(3, 'League of Legends Worlds 2026 - Grand Final',
    '2026-11-02 17:00:00', '2026-09-15 10:00:00', 'Draft',
    '[
        {"name":"Final Surge", "type":"sold_pct", "threshold":95, "modifier_pct":30}
    ]',
    NULL);   -- all channels allowed


-- -----------------------------------------------------------------------------
-- 4.3 SEATS (sample only — Python generates full seat inventory)
-- -----------------------------------------------------------------------------

-- Wembley (stadium 1)
INSERT INTO SEAT (stadium_id, seat_row, seat_number, seat_name, seat_type) VALUES
(1, 'A', '01', 'VIP_A01',    'vip'),
(1, 'A', '02', 'VIP_A02',    'vip'),
(1, 'B', '01', 'NORMAL_B01', 'normal'),
(1, 'B', '02', 'NORMAL_B02', 'normal'),
(1, 'C', '01', 'ECONOMY_C01','economy');

-- Tokyo Dome (stadium 2)
INSERT INTO SEAT (stadium_id, seat_row, seat_number, seat_name, seat_type) VALUES
(2, 'A', '01', 'VIP_A01',    'vip'),
(2, 'A', '02', 'VIP_A02',    'vip'),
(2, 'B', '01', 'NORMAL_B01', 'normal'),
(2, 'B', '02', 'NORMAL_B02', 'normal'),
(2, 'C', '01', 'ECONOMY_C01','economy');

-- Madison Square Garden (stadium 3)
INSERT INTO SEAT (stadium_id, seat_row, seat_number, seat_name, seat_type) VALUES
(3, 'A', '01', 'VIP_A01',    'vip'),
(3, 'B', '01', 'NORMAL_B01', 'normal'),
(3, 'C', '01', 'ECONOMY_C01','economy');


-- -----------------------------------------------------------------------------
-- 4.4 EVENT_ZONE
-- -----------------------------------------------------------------------------

--- Event 1: UCL Final (Wembley)
INSERT INTO EVENT_ZONE (event_id, seat_type, zone_name, base_price) VALUES
(1, 'vip',     'Platinum Hospitality',      25000000),
(1, 'normal',  'Category 1 - Lower Tier',    8000000),
(1, 'economy', 'Category 3 - Upper Tier',    3000000);

-- Event 2: Taylor Swift (Tokyo Dome)
INSERT INTO EVENT_ZONE (event_id, seat_type, zone_name, base_price) VALUES
(2, 'vip',     'Karma is My Boyfriend (Standing)', 15000000),
(2, 'normal',  'Lower Arena (Seated)',               6500000),
(2, 'economy', 'Restricted View',                    1500000);

-- Event 3: LoL Worlds (MSG)
INSERT INTO EVENT_ZONE (event_id, seat_type, zone_name, base_price) VALUES
(3, 'vip',     'Pro Player Lounge', 12000000),
(3, 'normal',  'Lower Bowl',         4000000),
(3, 'economy', 'Upper Bowl',         2000000);


-- -----------------------------------------------------------------------------
-- 4.5 EVENT_SEAT (populate inventory from seats above)
-- -----------------------------------------------------------------------------
INSERT INTO EVENT_SEAT (event_id, seat_id, zone_id)
    SELECT 
        e.event_id, 
        s.seat_id, 
        ez.zone_id
    FROM EVENT e
    JOIN SEAT s ON e.stadium_id = s.stadium_id
    JOIN EVENT_ZONE ez ON e.event_id = ez.event_id AND s.seat_type = ez.seat_type;


-- -----------------------------------------------------------------------------
-- 4.6 CUSTOMER
-- Row 1 is reserved for anonymous walk-in purchases.
-- -----------------------------------------------------------------------------
INSERT INTO CUSTOMER (customer_name, email, phone_number) VALUES
('Walk-in / Anonymous', NULL,                       NULL),
('Anne William',        'anne0909@gmail.com',        '0901234567'),
('Robert Lane',         'robland838338@gmail.com',   '0919876543');


-- -----------------------------------------------------------------------------
-- 4.7 BOX_OFFICE
-- -----------------------------------------------------------------------------
INSERT INTO BOX_OFFICE (office_name, office_type, stadium_id, commission_rate, address) VALUES
('Official Website',       'Online', NULL, 0.00, NULL),
('Wembley Ticket Counter', 'Venue',  1,    0.00, 'Wembley Stadium, London HA9 0WS'),
('Ticketmaster UK',        'Agent',  NULL, 10.00,'ticketmaster.co.uk');


-- -----------------------------------------------------------------------------
-- 4.8 TICKET (one sample paid transaction)
-- -----------------------------------------------------------------------------
SET @test_seat = (
    SELECT event_seat_id FROM EVENT_SEAT WHERE event_id = 1 LIMIT 1
);

INSERT INTO TICKET (event_seat_id, customer_id, box_office_id,
                    status, price_paid, price_reason, paid_at, qr_code)
VALUES (@test_seat, 2, 1, 'Paid', 22500000, 'Early Bird: -10%', NOW(), UUID());

-- Mark the seat as booked (trigger handles this in production, done manually here)
UPDATE EVENT_SEAT
SET status = 'Booked'
WHERE event_seat_id = @test_seat;
